console.log('hello');

const htmlDivElement=document.getElementById('htmldiv');
 const reactjsDivElement=document.getElementById('reactdiv');
 const renderloop = () =>{
	htmlDivElement.innerHTML='<div class="demo">Hello This is generated by JS</div><input value=""> </input> <p>' +new Date()+ '</p>';
 	ReactDOM.render(
		React.createElement("div",{className:"demo"},"Hello This is generated by ReactJS",
		React.createElement("br"),
		React.createElement("input",null,null),
		React.createElement("p",null,new Date().toString()) 
		),
		reactjsDivElement
		);
}
 setInterval(renderloop,1000); 